### ISSUE TITLE
Make a better logo

### ISSUE THREAD

**Issue by stephenmcm** [SilbinaryWolf/silverstripe-mrfilter#1]
I feel the low quality and frankly ugly logo really detracts from what is otherwise an excellent module.

**Comment by silbinarywolf** [comment]
If you actually inspect the image, you'll see that its a PNG and therefore of high quality. I think you need a bit more experience in the industry before you comment on the quality of peoples work.

In the future, please keep issues related to code only. This logo is non-negotiable and I spent a painstaking amount of time in MS-Paint building it from scratch, with no dependencies.

Thanks for your time and thanks for using my module.
