### ISSUE TITLE
Alternative to manyManyComponent() for backwards compatibility

### ISSUE THREAD

**Issue by gheggie** [SilbinaryWolf/silverstripe-mrfilter#25]
In `ListFilterUtility::filter_by_relation_ids()` there's a call to `singleton($class)->manyManyComponent($relationName)` however this method doesn't exist in 3.1.

An alternative might be something like:

```
$classObj = singleton($class);
$manyManyInfo = $classObj->hasMethod('manyManyComponent') ? 'manyManyComponent' : 'many_many';
list($parentClass, $componentClass, $myIDColumnName, $relationIDColumnName, $manyManyTable) = $classObj->$manyManyInfo($relationName);

**Comment by silbinarywolf** [comment]
Resolved in: https://github.com/SilbinaryWolf/silverstripe-mrfilter/pull/27
