### ISSUE TITLE
TotalItems() fix/workaround for framework bug in 3.1

### ISSUE THREAD

**Issue by gheggie** [SilbinaryWolf/silverstripe-mrfilter#26]
In `ListFilterForm::ShowingMessage()` the code `$data['TotalCount'] = $list->TotalItems();` throws an error due to a 3.1 bug in framework, with the workaround of calling `getTotalItems()` instead of `TotalItems()`.

See: (issue) https://github.com/silverstripe/silverstripe-framework/issues/2259 and (fix) https://github.com/silverstripe/silverstripe-framework/pull/4630

Can the mrfilter code be changed to use the workaround?

**Comment by silbinarywolf** [comment]
Resolved in: https://github.com/SilbinaryWolf/silverstripe-mrfilter/pull/27
