### ISSUE TITLE
Currently showing starts at "0"

### ISSUE THREAD

**Issue by Neumes** [SilbinaryWolf/silverstripe-mrfilter#5]
This should really be :
`$result->OffsetStart = $list->getPageLength() * ($result->CurrentPage - 1) + 1;`
instead of :
`$result->OffsetStart = $list->getPageLength() * ($result->CurrentPage - 1);`

There's also an issue where this is using the current page, although the url parameter takes the start index of items, so for example if you have 20 items displaying, but have a start index of 10, it will grab that it's the first page and return that it's showing 0-20 (or 1-20 after fix) and not 10-30 (11-30 after fix). I'll PR the code change above, and we can review the other part later when we have more time.

**Comment by silbinarywolf** [comment]
Made the issue concise elsewhere: https://github.com/SilbinaryWolf/silverstripe-mrfilter/issues/7
